background-color=#$surface
text-color=#$foreground
border-color=#$mako_border
progress-color=over #$accent

[urgency=low]
text-color=#$mako_low_text
border-color=#$mako_border

[urgency=critical]
background-color=#$urgent_surface
text-color=#$foreground
border-color=#$urgent
