background-color=#3c3836
text-color=#ebdbb2
border-color=#504945
progress-color=over #7daea3

[urgency=low]
text-color=#bdae93
border-color=#504945

[urgency=critical]
background-color=#432e26
text-color=#ebdbb2
border-color=#ea6962
