monitor = ,preferred,auto,1

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

$terminal = kitty
$menu = wofi --show drun

exec-once = mako
exec-once = lxpolkit
exec-once = hypridle

bind = SUPER, Return, exec, $terminal
bind = SUPER, D, exec, $menu
bind = SUPER, Q, killactive,
bind = SUPER, M, exit,
bind = SUPER, F, fullscreen,
bind = SUPER, SPACE, togglefloating,

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4

bind = SUPER CTRL, H, movecurrentworkspacetomonitor, l
bind = SUPER CTRL, L, movecurrentworkspacetomonitor, r

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 0
}
