$font = JetBrains Mono

general {
    hide_cursor = false
}

background {
    monitor =
    color = rgb(1d2021)
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgb(83a598)
    check_color = rgb(b8bb26)
    fail_color = rgb(fb4934)
    font_color = rgb(ebdbb2)
    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL
    fade_on_empty = false
    rounding = 8
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = $font
    color = rgb(ebdbb2)
    position = 0, 100
    halign = center
    valign = center
}
