general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

# Lock after fifteen minutes of inactivity.
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# Turn displays off after the session has been locked for 5 minutes.
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

# Suspend after 30 minutes of inactivity.
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
