# Keep the default tmux prefix on servers to make nested local/remote tmux
# sessions easier to reason about.
set-option -g prefix C-b
bind-key C-b send-prefix

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# ESC key fix
set -sg escape-time 8

# Vi mode
set -g mode-keys vi

# Vi mode key bindings for copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi 'C-b' send -X begin-selection \; send -X rectangle-on
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# override incorrect previous binding
bind p previous-window

# Vi mode pane switching with Ctrl+h/j/k/l (vim-tmux-navigator)
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Window navigation with Alt
bind -n M-n next-window
bind -n M-p previous-window

# alias for syncing panes
bind-key V setw synchronize-panes\; display "Synchronization: #{?pane_synchronized,on,off}"

# alias for tree view of windows and panes
bind-key S choose-tree -Z

# Update environment variables
set-option -g update-environment "\
  SSH_AUTH_SOCK \
  SSH_CONNECTION \
  DISPLAY"

# Terminal
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-features ",xterm-kitty:RGB"

# vim: set ft=tmux tw=0 nowrap:tmux
