[Settings]
# TODO: Keep GTK Medium until the external Hard theme is tested separately.
gtk-theme-name=Everforest-Green-Dark-Compact-Medium
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=default
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=1
