# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# ESC key fix
set -sg escape-time 8

# Vi mode
set -g mode-keys vi

# Vi mode key bindings for copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi 'C-b' send -X begin-selection \; send -X rectangle-on
bind -T copy-mode-vi y if-shell "uname -s | grep -q Darwin" \
    "send-keys -X copy-pipe 'pbcopy'" \
    "send-keys -X copy-pipe 'wl-copy --type text/plain'"
bind -T copy-mode-vi Enter if-shell "uname -s | grep -q Darwin" \
    "send-keys -X copy-pipe-and-cancel 'pbcopy'" \
    "send-keys -X copy-pipe-and-cancel 'wl-copy --type text/plain'"

# override incorrect previous binding
bind p previous-window

# Paste from system clipboard
bind-key C-p if-shell "uname -s | grep -q Darwin" \
    "run \"pbpaste | tmux load-buffer - ; tmux paste-buffer\"" \
    "run \"wl-paste --no-newline | tmux load-buffer - ; tmux paste-buffer\""

# Vi mode pane switching with Ctrl+h/j/k/l (vim-tmux-navigator)
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Window navigation with Alt
bind -n M-n next-window
bind -n M-p previous-window

# alias for syncing panes
bind-key V setw synchronize-panes\; display "Synchronization: #{?pane_synchronized,on,off}"

# alias for tree view of windows and panes
bind-key S choose-tree -Z

# Update environment variables
set-option -g update-environment "\
  SSH_AUTH_SOCK \
  SSH_CONNECTION \
  DISPLAY \
  WAYLAND_DISPLAY \
  XDG_RUNTIME_DIR \
  HYPRLAND_INSTANCE_SIGNATURE"

# Start panes/windows in zsh so shell functions from .zshrc are available.
set-option -g default-shell /usr/bin/zsh
set-option -g default-command "/usr/bin/zsh -l"

# Colors
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-features ",xterm-kitty:RGB,foot:RGB"

source-file ~/.local/state/dotfiles/theme/current/tmux.conf

# vim: set ft=tmux tw=0 nowrap:tmux
