## name: Everforest Dark Hard
## authors: Sainnhe Park, Emil Lofquist
## license: MIT
## upstream: https://github.com/ewal/kitty-everforest/blob/master/themes/everforest_dark_hard.conf
## modified: selection and tab colors use the current semantic palette

foreground                      #d3c6aa
background                      #272e33
selection_foreground            #d3c6aa
selection_background            #414b50

cursor                          #d3c6aa
cursor_text_color               #2e383c

url_color                       #7fbbb3

active_border_color             #a7c080
inactive_border_color           #4f5b58
bell_border_color               #e69875
visual_bell_color               none

active_tab_foreground           #a7c080
active_tab_background           #374145
inactive_tab_foreground         #859289
inactive_tab_background         #2e383c
tab_bar_background              #272e33
tab_bar_margin_color            none

mark1_foreground                #272e33
mark1_background                #7fbbb3
mark2_foreground                #272e33
mark2_background                #d3c6aa
mark3_foreground                #272e33
mark3_background                #d699b6

color0                          #2e383c
color1                          #e67e80
color2                          #a7c080
color3                          #dbbc7f
color4                          #7fbbb3
color5                          #d699b6
color6                          #83c092
color7                          #859289
color8                          #7a8478
color9                          #e67e80
color10                         #a7c080
color11                         #dbbc7f
color12                         #7fbbb3
color13                         #d699b6
color14                         #83c092
color15                         #9da9a0
