shell /usr/bin/zsh

font_family JetBrainsMono Nerd Font Mono
font_size 12.5

hide_window_decorations yes

tab_bar_style powerline
tab_bar_background #282828
tab_active_foreground #282828
tab_active_background #d79921
tab_inactive_foreground #ebdbb2
tab_inactive_background #3c3836
tab_title_template "{index}: {title}"

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME
